### ISSUE TITLE
Regenerate MIR outputs of `compiletest-rs/ui` to obtain simpler and cleaner MIR file

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#168]
At this moment, we should make use of the `rustc` flags to generate cleaner and less optimized MIR outputs in the `compiletest-rs/ui` suite: https://github.com/runtimeverification/mir-semantics-compiletest

The current generated outputs contains massive comments, `promotes` and debug assertions that are not needed now and in near future.

I've attempted regenerating the test cases, it failed because some of the features are removed from the latest rustc nightly version
`rustc 1.72.0-nightly (46514218f 2023-06-20)` .

For the current development, let's fix on this nightly version.

Furthermore, the compile test suite are updated as well, we might treat the suite directly as a sub-repo instead of keeping [our own](https://github.com/runtimeverification/mir-semantics-compiletest). 

[Commands in generating mir](https://github.com/runtimeverification/mir-semantics-compiletest) could be moved to the main [Makefile](https://github.com/runtimeverification/mir-semantics). You may also reference the make commands here: https://github.com/runtimeverification/mir-semantics/blob/feature/basic-operations/kmir/src/tests/integration/test-data/handwritten-rust/Makefile

**Comment by dkcumming** [comment]
I'm just trying to understand and navigate myself to the problem. What is the workflow to reproduce the problem? I cloned the [UI test repo](https://github.com/runtimeverification/mir-semantics-compiletest) but `make ui-mir` ran into an error - was this expected to pass or is it on a tangent to this issue?

**Comment by dkcumming** [comment]
From what I can see so far, I can't find any options to remove the comments in the compilation process for MIR. We can remove them with `sed` as post processing immediately after generating the file. How does this sound?

**Comment by yanliu18** [comment]
> From what I can see so far, I can't find any options to remove the comments in the compilation process for MIR. We can remove them with `sed` as post processing immediately after generating the file. How does this sound?

The `-Z` flag in the nightly feature will remove the comments.
You may want to refer to https://github.com/runtimeverification/mir-semantics/tree/master/kmir#get-mir-files-from-rust-programs and examples here: https://github.com/runtimeverification/mir-semantics/blob/feature/basic-operations/kmir/src/tests/integration/test-data/handwritten-rust/Makefile

**Comment by yanliu18** [comment]
I've attempted regenerating the test cases, it failed because some of the features are removed from the latest rustc nightly version
`rustc 1.72.0-nightly (46514218f 2023-06-20)` .

For the current development, let's fix on this nightly version.

Furthermore, the compile test suite are updated as well, we might treat the suite directly as a sub-repo instead of keeping [our own](https://github.com/runtimeverification/mir-semantics-compiletest).

**Comment by yanliu18** [comment]
@dkcumming I attempted to reproduce the result such that we could have statistics regarding the changes of the test suits.

The old test suit using `rustc stable 1.67` and compiling with specific rust editions generates 3197 test cases.

The exisiting one used `nightly-2023-07-09` generates (on ubuntu 22.04, Mac OS has minor differences) 2550 test cases (note that with [PR#2](https://github.com/runtimeverification/mir-semantics-compiletest/pull/2), our test suite synced with the changes in rust-lang repo). The reduce of test cases are due to:
1.  some test cases are removed due to the language feature change;
2. we ignore test cases which require a special edition of rust (some language features such as `async` is not supported in Rust@2015). 

With the exisiting one, tested on branch `refactor/builtin-identifiers`, there is `2134 failed, 416 passed`.
I am a bit surprised with so many failures. It looks like there are agressive changes for example `PointCoercion` and a branching syntax for some asserts `unwind continue` are both not supported by the current kmir parser.

While using the version `rustc 1.72.0-nightly (46514218f 2023-06-20)`, the `kmir-parse` test was `1520 failed, 1030 passed`.

I'd prefer to roll the rustc version back to `rustc 1.72.0-nightly (46514218f 2023-06-20)` to avoid those new changes changes, referred to [PR #4](https://github.com/runtimeverification/mir-semantics-compiletest/pull/4).
