### ISSUE TITLE
CI failed due to the compiletest was not updated

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#177]
Referring to the CI failure for PR #176: https://github.com/runtimeverification/mir-semantics/actions/runs/5532415489/jobs/10094488826?pr=176

The integration test is still using the old test suits with 3197 test cases where the [latest update in compiletest](https://github.com/runtimeverification/mir-semantics-compiletest/pull/2), it should be 2550 test cases.

Docker on CI needs to be rebuild.

**Comment by dkcumming** [comment]
The submodule needs to be commited correctly when it has been updated. To tell if the submodule is pointing at the correct location, `cat .git/modules/path-to-submodule/HEAD` should output the current hash of the submodule project. If it is not, the documentation to update the submodule is located [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules), take note of `--remote`, `--merge`, `--rebase` as options.
