### ISSUE TITLE
`kprove` claim parser has conflict between `LocalToken` and an unused variable

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#189]
### Description

MIR defines Local Places with a proceeding [underscore to an index](https://github.com/runtimeverification/mir-semantics/blob/eabc47ed136ace79644d3dab6a2962fb0cf616b2/kmir/k-src/mir-lexer-syntax.md?plain=1#L22) in local memory ([example from compiled source](https://github.com/runtimeverification/mir-semantics-compiletest/blob/916aed100259eff87d5b82f280b1a0078c6f5be6/ui/big-literals.mir#L219)). For example, to storing the result of `3 + 5` at local memory index 3 in MIR is:
```
_3 = Add(const 3_usize, const 5_usize)
```
However this appears to conflict with internal `k` syntax. Attempting to parse this line
```
claim <k> #executeStatement(_3 = Add(const 3_usize, const 5_usize)) => .K ...</k>
```
results in this error
```
[Error] Inner Parser: Parse error: unexpected token '_3' following token '('.
	Source(/home/daniel/Applications/mir-semantics/kmir/src/tests/proofs/simple-spec.k)
	Location(39,33,39,35)
	39 |	    claim <k> #executeStatement(_3 = Add(const 3_usize, const 5_usize))  => .K ...</k> 
           .                                                         ^~
```

`k` syntax uses a preceding underscore for a variable in LHS that is unused in RHS e.g.: 
```
claim <k> _A *Int 0 => 0 ... </k>
```
However replacing the letter `A` with the number `3` creates this error:
```
[Error] Inner Parser: Parse error: unexpected token '*Int' following token '_3'.
	Source(/home/daniel/Applications/mir-semantics/kmir/src/tests/proofs/simple-spec.k)
	Location(52,18,52,22)
	52 |	    claim <k> _3 *Int 0 => 0 ... </k>
	   .	                          ^~~~
```

### Work Arounds
We can use the function `#token` like so, 
```
claim <k> #executeStatement(#token("_3","LocalToken") = Add(const 3_usize, const 5_usize)) => .K ...</k>
```
however this would require a translator from the compiled MIR substituting Local occurrences, and feedback to the user would need to be translated back into MIR. This is not an ideal solution as it creates another point of failure in the system.

### Ideal Solution
Use escape characters, or configure `_{number}` to be permissible for this project.

**Comment by radumereuta** [comment]
When having lexical conflicts, the preferred solution is to use the `#token("val", "Sort")` construct.
This way, you completely avoid the problem in the first place.
You also need to pay attention to where you define the lexical production of your token. You can include it in the syntax module, but it should not be included in the semantics module.

**Comment by yanliu18** [comment]
@radumereuta this is the configuration file: https://github.com/runtimeverification/mir-semantics/blob/feature/kprove/kmir/src/tests/proofs/simple-spec.k
This error is coming from the pyk library. 
@dkcumming could provide more information here.

**Comment by dkcumming** [comment]
Adding `syntax LocalToken ::= _3` to the `VERIFICATION` module solves the issue for this example. Is there some way that we would be able to populate the module automatically with the amount of local memory locations that are used in the `MIR` file?

**Comment by dkcumming** [comment]
The error is not localised to `pyk`, if you run `kprove` directly without the addition to the `VERIFICATION` module above the same error occurs.

**Comment by radumereuta** [comment]
You can declare a more general token:
```
syntax LocalToken ::= r"_[0-9]+" [token]
```
Not sure about the syntax. I haven't tested it. But something like this should work.
