### ISSUE TITLE
Add nix to CI

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#198]
Nix install is now working, however it is not tested on CI. Integration tests should also be run on nix. This might require some adjustment to the way the integration tests are run.

**Comment by dkcumming** [comment]
After looking at CI for kevm, I think we do not need to test the whole integration test suite, and just each feature of kmir (`kmir parse` and `kmir run` currently).

**Comment by yanliu18** [comment]
> After looking at CI for kevm, I think we do not need to test the whole integration test suite, and just each feature of kmir (`kmir parse` and `kmir run` currently).

We are still actively developing KMIR semantics, we will need to test the integration test suite to ensure nothing is broken.

**Comment by dkcumming** [comment]
I'm not sure that we need to test it with nix again though. The same semantics that the nix distribution is built on will be tested in a different job. If we do want to test all the integration tests on nix again, we will need to set up a different way to run them, as the `pytest` environment is not included in the nix build - which is possible of course.
