### ISSUE TITLE
`KMIR` object and `llvm`/`haskell` dependencies

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#208]
### Context
`KMIR` currently supports two backends (`llvm` and `haskell`) and three operations (`parse`, `run`, and `prove`). The relationship between these backends and the operations is:
- llvm
    - parse
    - run
- haskell
    - prove  

### Problem
Currently it is assumed that the `haskell` backend [isn't needed](https://github.com/runtimeverification/mir-semantics/blob/f5788894bac628792fcb2054446a763697d63906/kmir/src/kmir/kmir.py#L62), and that the `llvm` backend [is needed](https://github.com/runtimeverification/mir-semantics/blob/f5788894bac628792fcb2054446a763697d63906/kmir/src/kmir/kmir.py#L46). This is because previously the only operations offered were `parse` and `run`, however now that `prove` is supported this need to be changed.

### Solution
I think there are three possible solutions:
1. A simple but obtuse solution would be to require both backend's definitions are built and provided, this is not ideal as the user should only be required to provide what is necessary.
2. Keep the structure mostly the same, and add conditional logic based on the operation. I think this is acceptable but also not ideal.
3. Restructure and refactor `KMIR` to be more representative of `KEVM`. This would meant that `KMIR` [directly inherits](https://github.com/runtimeverification/evm-semantics/blob/3c207e4102ced6038e3da95100b82507952c650c/kevm-pyk/src/kevm_pyk/kevm.py#L119) from both `KProve` and `KPrint`, instead of [storing the `KProve` object](https://github.com/runtimeverification/mir-semantics/blob/f5788894bac628792fcb2054446a763697d63906/kmir/src/kmir/kmir.py#L32) and `KMIR` indirectly accessing `_krun` [through a wrapper function](https://github.com/runtimeverification/mir-semantics/blob/f5788894bac628792fcb2054446a763697d63906/kmir/src/kmir/kmir.py#L142). I believe doing this will also mean we do not have to [call `kmir init` to create the syntax file for the `glr parser` in the `nix` build](https://github.com/runtimeverification/mir-semantics/blob/f5788894bac628792fcb2054446a763697d63906/flake.nix#L68). I think this option is preferable, although it will take more time than 2.

**Comment by yanliu18** [comment]
This issue might be closed as well. @dkcumming 
As the `haskell_dir` is now optional (I beliveve it is the same as you meant for conditional logic, no?).
The left over issue is to generate the `gen_glr_parser` at build time, which is this issue #280 .

Are you OK with closing it? or We can wait till the refactor PR is merged (should need one more week).
