### ISSUE TITLE
[BUG] Crash for `kmir run --output` if `output` is either `program`, `json`, `kast`

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#214]
### Problem
`kmir run` crashes on working tests if `--output` is changed to either `program`, `json`, `kast`

### Reproducer
```
cd mir-semantics/kmir
poetry update
make build
source set_env.sh
```
either:
```
poetry run kmir run --output kast src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir 
poetry run kmir run --output program src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir 
poetry run kmir run --output json src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir 
```
### Investigation
Output exists for specified a specified depth before crashing:
```
poetry run kmir run --debug --verbose --output program --depth 0 src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir
poetry run kmir run --debug --verbose --output kast --depth 3 src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir
poetry run kmir run --debug --verbose --output json --depth 3 src/tests/integration/test-data/handwritten-rust/const-arithm-simple.mir 
```

### Solution
Unknown at this stage, all three options are permissible according to [pyk](https://github.com/runtimeverification/pyk/blob/ca97bb1caf81ddbb70c87d9aa7be1a4b5385fb2b/src/pyk/ktool/krun.py#L29). It might not be worth fixing this directly, and instead changing the `KMIR` object and call to `run` as outlined in `Solution 3.` of #208

**Comment by yanliu18** [comment]
I am closing this issue, as the output options of `json` and `kast` are working now.
The `program` option crashed due to an K bug: https://github.com/runtimeverification/k/issues/3861
