### ISSUE TITLE
kmir not found in kup installed version

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#267]
Well, the error message is a simple `FILE-NOT-FOUND` if running `kmir -h` from any directory after installation.
```
bash: ~/.local/bin/kmir: No such file or directory
```
OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

More checking, `kup list` shows KMIR installed:
```
┌──────────────────────┬────────────────────────────────────────────────────┬────────────────────────────┐
│ Package name (alias) │ Installed version                                  │ Status                     │
├──────────────────────┼────────────────────────────────────────────────────┼────────────────────────────┤
│ kup                  │ 8194e49f78f9175b5d574998d11a968d149732ec           │ 🟢 installed               │
│ kevm                 │ ab2e2bf1deda7532457aead670e2582ad6397503           │ 🟠 newer version available │
│ k                    │ ce56ce7f79bbbfe77bac32bbee8476d2d29ddffc (v6.1.24) │ 🟠 newer version available │
│ kmir                 │ 6afeae677ed15d39e21dd8713a12356c5ed6bfa2           │ 🟢 installed
```

**Comment by yanliu18** [comment]
@dkcumming hey, we need to fix this as well.

**Comment by dkcumming** [comment]
There isn't meant to be anything at that local from the `nix` build. `nix` has it's own `bin` folder in the `.nix-profile`:
```
```

**Comment by yanliu18** [comment]
@dkcumming, Yeah, that should be the reason. `which kmir` does return `~/.nix-profile/bin/kmir`.
I've uninstalled `kmir` using `pip`, but somehow the system still finds`kmir` command from local bin. 
I do also have `.nix-profile` in my path.  
I am in the process of testing everything for writing the manual. 
I'll unsign this issue to you then.
@tothtamas28 do you have any ideas of how to solve this issue.

**Comment by dkcumming** [comment]
I just had a play around. Probably what happened is your project is still in the `pip` projects. Maybe try `pip list | grep kmir` to see if it is indeed still installed. If it is installed `pip uninstall kmir` should do it I believe.

**Comment by yanliu18** [comment]
@dkcumming thanks for trying it out.
nope, `pip list | grep kmir` returns nothing. 
I `pip uninstall kmir` ed before install via `kup`.

And the problem is removed by restarting the machine.
