### ISSUE TITLE
Opt in to new type inference method

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/mir-semantics#286]
@Scott-Guest has implemented a new type inference algorithm that does not rely on Z3; using it should reduce CI flakiness during parsing by not requiring a lot of files to be opened and processes to be spawned.

At the moment, the new mode is opt-in and can be enabled by passing:
```
--type-inference-mode simplesub
```
as a flag to `kompile`.

**Comment by dkcumming** [comment]
@Scott-Guest @Baltoli Just trying to understand, so the new type inference algo is in K >= v6.1.42 and we should go ahead and make the change now? Or it is still in development? I ask because this is part of K Development project also I see.

**Comment by Baltoli** [comment]
It's merged to K now, yes. The new algorithm is ready for use in downstream semantics but requires a fallback to Z3 in a few limited cases - you should make the change now so that we can see that it's working properly in the wild

**Comment by dkcumming** [comment]
Okay sound good, we will get on it.
