### ISSUE TITLE
Add ability to specify a particular claim in a file to prove or view

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#303]
Proving and viewing failed proofs only works at the file level, the ability to select a proof from a file would be very handy.

**Comment by yanliu18** [comment]
PR #312 should have provided this functionality in `show-proof` and `view-proof`.
Note that, the `claim label` should be the same as the `proof id` in the current design, could be invalid if pyk changes its design.

**Comment by yanliu18** [comment]
@dkcumming would you verify if this issue is fixed?

**Comment by dkcumming** [comment]
For `view-proof` and `show-proof` this functionality works, but we aren't able to optionally restrict the prover to only prove a particular claim in a spec file currently. The whole spec file is provided and it proves every claim inside.

**Comment by yanliu18** [comment]
I see. We should be able to add a cmd option to do this by providing the claim label.
If it is not urgent, I can do it after I am back.
