### ISSUE TITLE
CI Timing on daniel@daniel-MS-7E06

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#308]
<table>
    <tr>
        <th>commits</th>
        <th colspan="2">real: w/o booster</th>
        <th colspan="2">user: w/o booster</th>
        <th colspan="2">sys: w/o booster</th>
        <th>notes</th>
    </tr>
    <tr>
        <td><a href=https://github.com/runtimeverification/mir-semantics/commit/41c2a6ab2bf36f6696875334af8891b33dc3e67b>master@41c2a6a</a></td>
        <td>3m11.596s</td>
        <td>1m0.706s</td>
        <td>3m14.730s</td>
        <td>1m9.662s</td>
        <td>0m8.368s</td>
        <td>0m3.690s</td>
        <td></td>
    </tr>
    <tr>
        <td><a href=https://github.com/runtimeverification/mir-semantics/commit/4c3b5aa6a00204c66cf8979a59425ab9fd0bb819>master@4c3b5aa</a></td>
        <td>3m15.456s</td>
        <td>1m2.728s</td>
        <td>3m18.684s</td>
        <td>1m11.782s</td>
        <td>0m8.333s</td>
        <td>0m3.738s</td>
        <td></td>
    </tr>
    <tr>
        <td><a href=https://github.com/runtimeverification/mir-semantics/pull/291/commits/48b1fec1086bc7e757d4502d542b5745d5978123>feature/new-type-inf@48b1fec</a></td>
        <td>3m16.076s</td>
        <td>1m2.643s</td>
        <td>3m19.125s</td>
        <td>1m12.220s</td>
        <td>0m7.850s</td>
        <td>0m3.347s</td>
        <td>Scott's new type inference algorithm</td>
    </tr>
    <tr>
        <td><a href=></a></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>​

| commits | use booster| real | user | sys | notes |
|----------|------------|-----|-----|-----|-----|
|[master@41c2a6a](https://github.com/runtimeverification/mir-semantics/commit/41c2a6ab2bf36f6696875334af8891b33dc3e67b) | y | 3m11.596s | 3m14.730s | 0m8.368s | |
|[master@41c2a6a](https://github.com/runtimeverification/mir-semantics/commit/41c2a6ab2bf36f6696875334af8891b33dc3e67b) | n | 1m0.706s | 1m9.662s | 0m3.690s | |
|[master@4c3b5aa](https://github.com/runtimeverification/mir-semantics/commit/4c3b5aa6a00204c66cf8979a59425ab9fd0bb819) | y | 3m15.456s | 3m18.684s | 0m8.333s | |
|[master@4c3b5aa](https://github.com/runtimeverification/mir-semantics/commit/4c3b5aa6a00204c66cf8979a59425ab9fd0bb819) | n | 1m2.728s | 1m11.782s | 0m3.738s | |
|[feature/new-type-inf@48b1fec](https://github.com/runtimeverification/mir-semantics/pull/291/commits/48b1fec1086bc7e757d4502d542b5745d5978123) | y | 3m16.076s | 3m19.125s | 0m7.850s | Scott's new type inference algorithm |
|[feature/new-type-inf@48b1fec](https://github.com/runtimeverification/mir-semantics/pull/291/commits/48b1fec1086bc7e757d4502d542b5745d5978123) | n | 1m2.643s | 1m12.220s | 0m3.347s | Scott's new type inference algorithm |

**Comment by dkcumming** [comment]
Real is the actual time passes. User is the combination of time on threads (not sure how this is calculated), and sys time are things from system operations so kernel operations I believe. At least this is how I've come to understand them.

**Comment by yanliu18** [comment]
> Real is the actual time passes. User is the combination of time on threads (not sure how this is calculated), and sys time are things from system operations so kernel operations I believe. At least this is how I've come to understand them.

Oh, i see. Good to know, thanks.
BTW, I revised your table to have the `colspan` look. It might be more straightforward for comparison.
Unfortunately, there is no `colspan` in github's markdown, I had to use the raw html.
Thus, I didn't delete the old table, in case you perfer the old table styple.
