### ISSUE TITLE
Migrate build from `kbuild` to `kdist`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/mir-semantics#310]
Source and documentation: https://github.com/runtimeverification/pyk/tree/master/src/pyk/kdist

As a `kdist` target executes arbitrary Python code, it also allows for generation of artifacts other than kompiled definitions, e.g. the GLR parser.

**Comment by yanliu18** [comment]
The current kbuild implementation works fine for us. 
Since we have other high priority tasks, we should delay addressing this issue to a future time when necessary.
