### ISSUE TITLE
Parsing meta-issue

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#327]
This issue is intended to categorise the issues that are occurring with parsing for KMIR. 'Parsing' here may refer to the parsing of either the LLVM parser, or the Haskell parser. However 'parsing' is distinct from 'extraction' which is the process of accessing the MIR from the rust compiler in some format (`--emit mir` for textual MIR, a `rustc_driver` program for a JSON dump). Currently the only extraction KMIR uses is [--emit mir](https://github.com/runtimeverification/mir-semantics/blob/baa8be0106bfaed776bde8e994bbf6acc8ce2759/kmir/src/tests/integration/test-data/run-rs/Makefile#L15) for [textual MIR](https://github.com/runtimeverification/mir-semantics/blob/master/kmir/src/tests/integration/test-data/run-rs/functions/sum-to-n.mir).

## Discrepancies between bison-glr parser and java parser handling ambiguities
Depending on which parser is used to run a test, the test may produce a different result
#235

## Claim parser will stall on any IdentifierToken that isn't explicitly listed in the verification module or spec file
#320 

## Syntax for project is based on [Rust surface language reference](https://doc.rust-lang.org/reference/types.html#type-expressions) which differs from MIR internal and stable mir
Progress was made on this in the branch [refactor/smir-syntax](https://github.com/runtimeverification/mir-semantics/tree/refactor/smir-syntax), however some challenges were encountered which inhibited merging including passing the test suite and handling the introduced ambiguities. 

## Parser hits unexpected tokens on stale branches
#171
#209

## Conflicts in textual MIR
#54 

## Other issues with parsing I'm unsure how to categorise
#85
#86
#87
#90
#91
#92
#93
#315

**Comment by yanliu18** [comment]
@dkcumming thank you. This issue summarises well. 
I think for issue #85 - 87, #90-93, they are refering to the exisiting syntax implementation and bison-glr parser issue.
We might probaly ignore them (but reference to these suggestions when problem was encountered) if new parser is to be implemented or if the syntax is refactored.
