### ISSUE TITLE
Figure out what it means to have a terminator without a destination

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/mir-semantics#77]
Most likely these calls always throw exceptions, and these exceptions are not handled by the caller.

Examples:

https://github.com/runtimeverification/mir-semantics-compiletest/blob/9251b00e38504a6f1279b0ca9f81b90b4964080d/ui/assign-assign.mir#L200
https://github.com/runtimeverification/mir-semantics-compiletest/blob/9251b00e38504a6f1279b0ca9f81b90b4964080d/ui/ufcs-polymorphic-paths.mir#L1843
https://github.com/runtimeverification/mir-semantics-compiletest/blob/9251b00e38504a6f1279b0ca9f81b90b4964080d/ui/array-slice-vec/box-of-array-of-drop-2.mir#L318

**Comment by yanliu18** [comment]
panic will terminate the program, I do not think it will need a destination.
