### ISSUE TITLE
StructRValue should probably use a more specific sort than Type

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/mir-semantics#81]
TODO: https://github.com/runtimeverification/mir-semantics/blob/07273e39e0435e7fbab7609dcd37636d2fb5a229/kmir/k-src/mir-syntax.k#L157

We should also check what the mir AST in rustc uses here.

**Comment by yanliu18** [comment]
This issue is closed as it is outdated. 
Th current implementtion of `Rvalue` is close to rustc implementation.

Besides, `Type` should referring to the type context which is no shown in MIR.
