### ISSUE TITLE
Make sure that all tokens in the semantics are whitelisted as identifiers

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/mir-semantics#90]
TODO: https://github.com/runtimeverification/mir-semantics/blob/07273e39e0435e7fbab7609dcd37636d2fb5a229/kmir/k-src/mir-syntax.k#L568

Defining something like
```
syntax DataAlloc ::= Identifier "(" MaybeStaticPath "size" ":" Int "," "align" ":" Int ")" "{" DataAllocData "}"
```

means that `size`, and `align` will not be parsed as `IdentifierToken`. The same is true for `AlignOf` in
```
syntax RValue ::= AlignOf(Type)
```

We should figure out all tokens that can be used, say, as struct names and whitelist them in order to be considered identifiers (or find a different solution).

**Comment by yanliu18** [comment]
I think we could close this issue. 
And since there is a lot of changes in the syntax and semantics definition. This issue might not be valid anymore.
@dkcumming what do you think?
